### ISSUE TITLE
New Framework Suggestion: TailwindCSS

### ISSUE THREAD

**Issue by skrantzman** [DNN-Connect/connect.koi#13]
Not sure if this project is dead or not, as there has not been a commit in a couple of years.  If it is still being maintained, I would like to suggest [TailwindCSS](https://tailwindcss.com/) be added to the list of supported platforms.  Not only do I believe that it meets the criteria for adding a new framework, I have just spent the time to created a theme development platform that utilizes it. [DNN_Tailwind](https://www.dnntailwind.com/) is based on [nvQuicktheme](https://nvquicktheme.com) by nvisionative, but I have ported the project over from utilizing Bootstrap 4 as the css framework to Tailwind CSS.  Tailwind has gained much traction in just two years, and I hope to make it a viable framework for DNN themes.

**Comment by iJungleboy** [comment]
Hi @skrantzman 

This project is very alive and maintained. It's actually just that it's very stable and has a very focused purpose, so there were no relevant changes necessary for a very long time (which is awesome :). 

I don't know tailwind - 3-char what abbreviation would make most sense, or is there an official abbreviation like `tlw`? Also are there common versions like `tw1` and `tw2` is on the roadmap or something? It's important as Koi works best when this convention is standardised and published here: https://connect-koi.net/css-frameworks

**Comment by iJungleboy** [comment]
I can see that it's currently on v1.6 - so it's probably better to use version numbers - maybe `tw1` - what do you think?

**Comment by skrantzman** [comment]
Hi @iJungleboy,

I am glad to hear that the project is very much alive and stable!  

When I first looked at Tailwind, I thought  this doesn't make sense, it's like going back to the days of inline styling. Why would anyone want to do that? We have had separation of concerns pounded into us for years.  But then I read more, was intrigued, and gave it a chance, and I really like what I am seeing with its non opinionated utility first classes.  I could go into a long explanation of what Tailwind CSS is and it benefits (and a few drawbacks), but here is not the place for that.  I do encourage you to take 1 minute to look at the first example of [Utility-First](https://tailwindcss.com/docs/utility-first) design on this page. You can quickly realize the benefits of Tailwind when you see how much less code (in the way of CSS) that you have to write compared to traditional html - css design techniques. Also just examining the animated gif at the top of the home page reveals much as well.

Here is graph of Tailwind's growth trend on npmtrends.com

![Tailwind Growth Trend NPM](https://user-images.githubusercontent.com/7874652/90267804-e74f6200-de0a-11ea-9f74-5ef0cf74103c.JPG)


I don't know if there is an official abbreviation used for Tailwind or not, but I think tlw would be great.  Adam Wathan who created Tailwind CSS, is stepping away from his normal job to focus on TLW full time, and now has a team working with him at TailwindLabs, so we can assume that new versions will be rolling out at a regular pace.

_Adam also has a great tutorial series on [Designing with Tailwind CSS](https://www.youtube.com/watch?v=21HuwjmuS7A&list=PL7CcGwsqRpSM3w9BT_21tUU8JN2SnyckR) on Youtube if interested._

**Comment by iJungleboy** [comment]
Sounds interesting. Without going too deep, I'm not sure though what is very different about this than Bootstrap. At least the Utility-First example you included feels very similar to Bootstrap. 

But that's basically for others to decide. I think adding `tlw`, `tw1` or `tlw1` to standardize this convention feels fairly simple. I suggest `tlw1` to be sure that future, breaking changes have a different identifier. 

Ok for you?

**Comment by skrantzman** [comment]
tlw1 sound great.

Thank you.

**Comment by iJungleboy** [comment]
Just added it to https://connect-koi.net/css-frameworks

BTW: If you would find time to create an edition of the content-templates using tailwind-css, that would be awesome and we would include it in the standard distribution :). 

If you're interested and would find time, I could guide you through it. I assume it would probably take you about 4-8 hours or so to do this.

**Comment by skrantzman** [comment]
I would be happy to help if it fall in my skill set.

**Comment by iJungleboy** [comment]
It's pretty simple - here's what you would have to do

1. Create a skin/theme using tailwind (which you probably already have)
1. Add the koi.json to the skin folder with the code `tlw1`
1. Install the standard content-templates of 2sxc in one of the newest versions of 2sxc  
there you will find a folder called `bs3` and the _root_ - these are the two editions that already exist. 
1. Now create a new folder called `tlw1` and copy all the important folders from the root into it.  
These are probably `Content`, `Image`, `Layout Element`, `Link`, `Location`, `Person`, `shared`, `Video` . In the end your folder should look similar to `bs3` which is also an alternate edition to the default `bs4` in the _root_
1. This will now automatically load these files when adding content-blocks to the page (because `tlw1` in the skin is detected, so it tries to load the templates in the folder `tlw1`)
1. Now start reworking the styles in that folder. You may need to adjust what css-files are loaded - usually in `shared/_assets.cshtml`

When done, just either mail them to info@ or add a pull-request to https://github.com/2sic/2sxc-content-app

**Comment by skrantzman** [comment]
I will take a look and see what I can do.  Do you have a timeframe?

**Comment by iJungleboy** [comment]
No, this would just be an added bonus or anybody trying to start with this - and would help that all your sites would automatically have Tailwind content - but ATM there isn't anybody pushing for this yet.
